create table scan_face_log (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    `channel_id` varchar(255) NOT NULL DEFAULT '' COMMENT '通道ID',
    `channel_name` varchar(255) NOT NULL DEFAULT '' COMMENT '通道名称',
    `face_image_url` varchar(255) NOT NULL DEFAULT '' COMMENT '人脸抓拍图片,如果涉及到内外网，地址 会以”|”分隔 ',
    `picture_url` varchar(255) NOT NULL DEFAULT '' COMMENT '场景图,如果涉及到内外网，地址会以”|” 分隔',
    `age` INT NOT NULL DEFAULT -1 COMMENT '年龄',
    `sex` INT NOT NULL DEFAULT -1 COMMENT '性别   0：未知，1：男， 2：女',
    `fringe` INT NOT NULL DEFAULT '' COMMENT '刘海   0 无，1 有 ',
    `eye` INT NOT NULL DEFAULT -1 COMMENT '眼镜   0 无，不显示，1 眼镜，2 墨',
    `mouth` INT NOT NULL DEFAULT -1 COMMENT '嘴型   1 未识别，2 闭嘴，3 张嘴',
    `mask` INT NOT NULL DEFAULT -1 COMMENT '口罩   1 未识别， 2 无口罩， 3 戴口罩 ',
    `beard` INT NOT NULL DEFAULT -1 COMMENT '胡子   1 未识别， 2 没胡子， 3 有胡子',
    `glasses` INT NOT NULL DEFAULT -1 COMMENT '眼镜   0 无，1 眼镜，2 墨镜',
    `emotion` INT NOT NULL DEFAULT -1 COMMENT '表情   0 微笑，1 愤怒，2 悲伤，3 厌恶， 4 害怕，5 惊讶，6 正常，7 大笑，8 高兴， 9 困惑，10 尖叫',
    `begin_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '表情   0 微笑，1 愤怒，2 悲伤，3 厌恶， 4 害怕，5 惊讶，6 正常，7 大笑，8 高兴， 9 困惑，10 尖叫',
    `end_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00' COMMENT '表情   0 微笑，1 愤怒，2 悲伤，3 厌恶， 4 害怕，5 惊讶，6 正常，7 大笑，8 高兴， 9 困惑，10 尖叫',
    `service_code` varchar(255) NOT NULL DEFAULT '' COMMENT '服务编码',
    `appear_times` INT NOT NULL DEFAULT -1 COMMENT '服务编码',
    `recognition` INT NOT NULL DEFAULT -1 COMMENT '服务编码',
    `flag` tinyint NOT NULL DEFAULT 0 COMMENT '标识删除，0：存在 1：删除',
    `creator` varchar(255) DEFAULT NULL COMMENT '创建人',
    `editor` varchar(255) DEFAULT NULL COMMENT '修改人',
    `create_time` datetime DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
    `edit_time` datetime DEFAULT '1970-01-01 00:00:00' COMMENT '更新时间',
)

create table scan_similar_face_log (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
    `scan_face_log_id` bigint NOT NULL DEFAULT 0 COMMENT '扫脸日志id',
    `face_image_url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '人脸库中图',
    `name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '名称',
    `person_type_id` INT NOT NULL DEFAULT -1 COMMENT '人员类型 1 学生 2 教师 3 保安 4 宿管 5 其他 ',
    `person_type_name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '人员类型名称',
    `person_id` bigint NOT NULL DEFAULT -1 COMMENT '人员学工号',
    `sex` INT NOT NULL DEFAULT -1 COMMENT '性别 0：未知，1：男， 2：女',
    `remark` text NOT NULL DEFAULT '' COMMENT '备注',
    `repository_id` bigint NOT NULL DEFAULT 0 COMMENT '人脸库 id',
    `repository_name` VARCHAR(255) NOT NULL DEFAULT 0 COMMENT '人脸库名称',
    `repository_color` INT NOT NULL DEFAULT 0 COMMENT '人脸库颜色 1-灰色 2-橙色',
    `similarity` INT NOT NULL DEFAULT 0 COMMENT '相似度',
    `phone` VARCHAR(255) NOT NULL DEFAULT 0 COMMENT '联系电话',
    `surveillance` INT NOT NULL DEFAULT 0 COMMENT '是否布控(可忽略)',
    `id_card` VARCHAR(255) NOT NULL DEFAULT 0 COMMENT '身份证',
    `birthday` datetime NOT NULL DEFAULT 0 COMMENT '生日',
    `uid` bigint NOT NULL DEFAULT 0 COMMENT '人员绑定库产生的 id',
    `nationality` VARCHAR(255) NOT NULL DEFAULT 0 COMMENT '国籍(可忽略)',
    `flag` tinyint NOT NULL DEFAULT '0' COMMENT '标识删除，0：存在 1：删除',
    `creator` varchar(255) DEFAULT NULL COMMENT '创建人',
    `editor` varchar(255) DEFAULT NULL COMMENT '修改人',
    `create_time` datetime DEFAULT '1970-01-01 00:00:00' COMMENT '创建时间',
    `edit_time` datetime DEFAULT '1970-01-01 00:00:00' COMMENT '更新时间',
)